[project]
name = "gap-scanner"
version = "0.1.0"
description = "gap_scanner"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "python-dotenv>=1.1.1",
    "tinkoff-investments>=0.2.0b115",
]
