name: CI

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get path
        run: echo ${GITHUB_WORKSPACE}

      - name: Update OS without interactive prompts
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -y
          sudo apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
          sudo apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
          sudo apt autoremove -y

      - name: Install docker
        run: |
          if [[ $(which docker) && $(docker --version) ]]; then true; 
          else
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo systemctl enable docker
            sudo systemctl start docker
          fi;

      - name: Create .env for all services
        env:
          TINKOFF_INVEST_TOKEN: ${{ secrets.TINKOFF_INVEST_TOKEN }}
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/src/gap_scanner"
          printf 'TINKOFF_INVEST_TOKEN=%s\nLOG_LEVEL=INFO\n' \
                "$TINKOFF_INVEST_TOKEN" \
              > "${GITHUB_WORKSPACE}/src/gap_scanner/.env"
          chmod 600 "${GITHUB_WORKSPACE}/src/gap_scanner/.env"

          mkdir -p "${GITHUB_WORKSPACE}/src/strategies"
          printf 'TINKOFF_INVEST_TOKEN=%s\nLOG_LEVEL=INFO\n' \
                "$TINKOFF_INVEST_TOKEN" \
              > "${GITHUB_WORKSPACE}/src/strategies/.env"
          chmod 600 "${GITHUB_WORKSPACE}/src/strategies/.env"

          mkdir -p "${GITHUB_WORKSPACE}/src/vwap_levels"
          printf 'TINKOFF_INVEST_TOKEN=%s\nLOG_LEVEL=INFO\n' \
                "$TINKOFF_INVEST_TOKEN" \
              > "${GITHUB_WORKSPACE}/src/vwap_levels/.env"
          chmod 600 "${GITHUB_WORKSPACE}/src/vwap_levels/.env"

          mkdir -p "${GITHUB_WORKSPACE}/src/orchestrator"
          printf 'TINKOFF_INVEST_TOKEN=%s\nLOG_LEVEL=INFO\n' \
                "$TINKOFF_INVEST_TOKEN" \
              > "${GITHUB_WORKSPACE}/src/orchestrator/.env"
          chmod 600 "${GITHUB_WORKSPACE}/src/orchestrator/.env"

      - name: Build, run docker and follow logs (15 min)
        run: |
          set -e
          cd ${GITHUB_WORKSPACE}
          docker compose -f docker-compose.yml build --no-cache
          docker compose -f docker-compose.yml up -d
          echo "::group::docker compose live logs"
          timeout 900 docker compose logs -f --no-color || true
          echo "::endgroup::"
          ls -l reports && head -n 5 reports/strategy_results.csv

      - name: Fail if report is missing
        run: test -f reports/strategy_results.csv

      - name: Commit strategy_results.csv
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: |
            chore(ci): update strategy_results.csv
          file_pattern: reports/strategy_results.csv

      - name: Docker image prune final
        run: |
          docker system prune -af
          sudo rm -rf /var/log/*
